# Generated by Django 4.1.5 on 2023-01-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_member',
            old_name='member_id',
            new_name='member_pk',
        ),
    ]
