# Generated by Django 4.1.5 on 2023-01-30 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hallinfo', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallinfo',
            name='provost_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.faculty_member'),
        ),
    ]
