# Generated by Django 4.1.5 on 2023-01-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallinfo', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('room_details_pk', models.AutoField(primary_key=True, serialize=False)),
                ('select_hall', models.CharField(max_length=100)),
                ('select_room', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=15, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('balance', models.FloatField()),
                ('comment', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
