# Generated by Django 4.1.5 on 2023-01-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallinfo', '0004_remove_roomdetails_select_hall_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomDetails',
            new_name='RoomDetail',
        ),
    ]
